version: '3'
services:
  api:
    #restart: always
    container_name: ms-lachec-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
